### ISSUE TITLE
Help configuring Forza-horizon

### ISSUE THREAD

**Issue by rckbi** [bennett-sh/contact#4]
Hi, I have a javascript background so typescript is somewhat foreign to me. Would you be open to helping me configure my UDP server? I have an xbox if that makes it tough. Feel free to contact me on email if you prefer: rickybillig@icloud.com

**Comment by bennett-sh** [comment]
Hello,
thanks for reaching out! What help would you like to have with setting up the server?

**Comment by rckbi** [comment]
In the README it looks like you are only inputting your port number. I am assuming that means you are playing on computer. Given I am playing on Xbox, I need to adjust your example to allow for ip address (send from xbox's ip to my computer's ip). Would you have an idea for how I can do that?

**Comment by bennett-sh** [comment]
You'll need to pass the address you want to bind to to the bind function.
```ts
server.bind('192.168.178.50' /* replace this with the IP of your PC*/)
```
The IP address will also have to be entered on your console under "data out ip address".

**Comment by bennett-sh** [comment]
Can you confirm if this worked once you've tried it?

**Comment by rckbi** [comment]
just to confirm, I add that to Main.js?

**Comment by bennett-sh** [comment]
[forza-server-example.zip](https://github.com/bennett-sh/contact/files/11152682/forza-server-example.zip)
This is how it could look. You'd only need to replace the thing in main.js with your local ip address.

**Comment by bennett-sh** [comment]
yes

**Comment by rckbi** [comment]
can't get it to work, but it may be something I am doing so I am going to play around with it.

**Comment by bennett-sh** [comment]
feel free to share your code and any error messages you get
