### ISSUE TITLE
the wemodprounlocker is down due to a dmca takedown, would it be possible for me to get the compiled cli executable?

### ISSUE THREAD

**Issue by Peanutnoodlez** [bennett-sh/contact#7]

**Comment by Icnopandaz** [comment]
Been a few months, unsure if you got a response or not - But asking for the same.

**Comment by bennett-sh** [comment]
[automated] I'm sorry but I won't be sharing the source code or any binaries related to WeMod Pro Unlocker/WMPU from this point onward due to past DMCA takedown requests. Thank you for your understanding.
